### ISSUE TITLE
Font download doesn't work

### ISSUE THREAD

**Issue by jumpinf00l** [bkbilly/placeholder_service#1]
Great add-on - just what I was looking for! Slight bug though sorry:

Specifying a font from the Google Fonts Repository doesn't seem to work correctly. Calling with `&font=FrederickatheGreat-Regular.ttf` works as expected, but the font is likely already downloaded ins this case.

Example: http://localhost:9845/?text=Hello\nworld!&font=Raleway.ttf

If calling the URL in a browser the response is: ERR_EMPTY_RESPONSE

This should download and use this font: https://fonts.google.com/specimen/Raleway

Console log:
```10.1.0.57 - - [14/Dec/2024 02:00:16] code 400, message Bad request version ('\\x8f&îþ]@{m¿vkÈè¯Ô\\x84+N*aµ\\\\\\x19~\\x8d')
10.1.0.57 - - [14/Dec/2024 02:00:16] "\x16\x03\x01\x06ä\x01\x00\x06à\x03\x03\x1fg·ÖêÃ\x1bÅ¡RóÚxÆ»Ô\x85¯`*7\x9d&\x13¨µ\x88ü÷ªÉÁ \x8f&îþ]@{m¿vkÈè¯Ô\x84+N*aµ\\\x19~\x8d" 400 -
10.1.0.57 - - [14/Dec/2024 02:00:16] code 400, message Bad request syntax ('\\x16\\x03\\x01\\x06Ä\\x01\\x00\\x06À\\x03\\x03÷Z´GáòfÍ\\x07\\x07\\x7fUNR÷Ø\\\\d\\x07îÐ$')
10.1.0.57 - - [14/Dec/2024 02:00:16] "\x16\x03\x01\x06Ä\x01\x00\x06À\x03\x03÷Z´GáòfÍ\x07\x07\x7fUNR÷Ø\\d\x07îÐ$" 400 -
Can't find font
```

**Comment by bkbilly** [comment]
This is not possible to fix, you will have to use the full name of the font because it relies on finding the exact name of the font from the [google's github repository](https://github.com/google/fonts).
In your case the font you are looking for is located [here](https://github.com/google/fonts/tree/main/ofl/raleway) which should result in one of the following URLs:
 - http://localhost:9845/?text=Hello%5Cnworld!&font=Raleway[wght].ttf
 - http://localhost:9845/?text=Hello%5Cnworld!&font=RalewayDots-Regular.ttf

Hope this clears things up.

**Comment by jumpinf00l** [comment]
That's perfect - thanks for the clarification
